export const TextConstants = {
    EMAIL_LABEL: 'Email',
    PASSWORD_LABEL: 'Password',
    EMAIL_PLACEHOLDER: 'type your email here',
    PASSWORD_PLACEHOLDER: 'type your password here',
    FORGOT_PASSWORD_LINK: 'Forgot password?',
    SIGNUP_LINK: 'Sign up',
    LOGIN_BUTTON: 'Login',
    SIGNUP_BUTTON: 'Sign up',
    API_RESPONSE_ERROR: 'An error has occurred',
    NEW_PATIENT_BUTTON: 'New Patient',
    SIDEBAR_DASHBOARD: 'Dashboard',
    SIDEBAR_PATIENTS: 'Patients',
    SIDEBAR_REPORTS: 'Reports',
    SIDEBAR_SEARCH: 'Search...',
  };