export const TextConstants = {
    NAME_LABEL: 'Name',
    EMAIL_LABEL: 'Email',
    PASSWORD_LABEL: 'Password',
    CONFIRM_PASSWORD_LABEL: 'Confirm your password',
    NAME_PLACEHOLDER: 'type your name here',
    EMAIL_PLACEHOLDER: 'type your email here',
    PASSWORD_PLACEHOLDER: 'type your password here',
    CONFIRM_PASSWORD_PLACEHOLDER: 'type your password confirmation here',
    FORGOT_PASSWORD_LINK: 'Forgot password?',
    SIGNUP_LINK: 'Sign up',
    REGISTER_BUTTON: 'Register now',
    LOGIN_BUTTON: 'Login',
    SIGNUP_BUTTON: 'Sign up',
    ALREADY_HAVE_ACCOUNT: 'Already have an account? click here to login',
    API_RESPONSE_ERROR: 'An error has occurred',
    NEW_PATIENT_BUTTON: 'New Patient',
    SIDEBAR_DASHBOARD: 'Dashboard',
    SIDEBAR_PATIENTS: 'Patients',
    SIDEBAR_REPORTS: 'Reports',
    SIDEBAR_SEARCH: 'Search...',
    WARNING_MESSAGE_TITLE: 'Warning',
    SUCCESS_MESSAGE_TITLE: 'Success',
    INFO_MESSAGE_TITLE: 'Info',
    ERROR_MESSAGE_TITLE: 'Error',
    LOGOUT_BUTTON: 'Logout'
  };